[package]
name = "mycelium-cli"
description = "Command line interface for mycelium"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "mycelium"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
mycelium-graph = { path = "../mycelium-graph" }
open.workspace = true
rust-embed.workspace = true
serde_json.workspace = true
tiny_http.workspace = true

[dev-dependencies]
tempfile = "3"
